-- Create tables on start up.

CREATE TABLE LIBRARY_USERS (ID INT PRIMARY KEY NOT NULL, NAME VARCHAR(255) NOT NULL, PHONE_NUMBER VARCHAR(255), EMAIL_ADDRESS VARCHAR(255));

CREATE TABLE LIBRARY_BOOKS (ID INT PRIMARY KEY NOT NULL, TITLE VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, ISBN VARCHAR(255) NOT NULL);

CREATE TABLE LIBRARY_BOOKS_LENT (USER_ID INT NOT NULL, BOOK_ID INT NOT NULL, FOREIGN KEY (USER_ID) REFERENCES public.LIBRARY_USERS(ID), FOREIGN KEY (BOOK_ID) REFERENCES public.LIBRARY_BOOKS(ID));